python: "3.10.5"
build_dependencies:
  - pip
dependencies:
  - torch==1.13.1+cu116
  - torchvision==0.14.1+cu116
  - mlflow
  - tqdm
  - pandas
  - black
  - flake8
  - matplotlib
  - mypy
  - opencv-python
  - Pillow
  - pyflakes
  - PyYAML
  - scikit-learn
  - scipy
  - tensorboard
  - types-PyYAML
